# Generated by Django 3.1 on 2020-08-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.IntegerField(unique=True),
        ),
    ]
