# Generated by Django 3.1 on 2020-08-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_auto_20200817_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
    ]
