# Generated by Django 3.1 on 2020-08-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_remove_user_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(null=True),
        ),
    ]
