# Generated by Django 3.1 on 2020-08-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_auto_20200817_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
