# Generated by Django 3.1 on 2020-08-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_auto_20200819_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('vk_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('access_token', models.TextField(null=True)),
            ],
        ),
    ]
