# Generated by Django 3.1 on 2020-08-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
